receivers:
  signozkafkareceiver/traces:
    topic: default_traces
    brokers:
      - ${KAFKA_BROKER_1}
      - ${KAFKA_BROKER_2}
      - ${KAFKA_BROKER_3}
    client_id: otel-collector
    group_id: otel-collector
    metadata:
      retry:
        max: 10
        backoff: 5s
    sarama_consumer_config:
      fetch_min_bytes: 1
      fetch_default_bytes: 64
      fetch_max_bytes: 128
      max_processing_time: 500ms
      messages_channel_size: 1024
      consumer_group_session_timeout: 30s

  signozkafkareceiver/logs:
    topic: default_logs
    # encoding: json
    brokers:
      - ${KAFKA_BROKER_1}
      - ${KAFKA_BROKER_2}
      - ${KAFKA_BROKER_3}
    client_id: otel-collector
    group_id: otel-collector
    initial_offset: earliest
    metadata:
      retry:
        max: 10
        backoff: 5s

  signozkafkareceiver/metrics:
    topic: default_metrics
    # encoding: direct
    brokers:
      - ${KAFKA_BROKER_1}
      - ${KAFKA_BROKER_2}
      - ${KAFKA_BROKER_3}
    client_id: otel-collector
    group_id: otel-collector
    initial_offset: earliest
    metadata:
      retry:
        max: 10
        backoff: 5s

exporters:
  clickhousetraces:
    datasource: tcp://${CLICKHOUSE_DB_HOST}:${CLICKHOUSE_DB_PORT}/signoz_traces
    docker_multi_node_cluster: ${DOCKER_MULTI_NODE_CLUSTER}
    low_cardinal_exception_grouping: ${LOW_CARDINAL_EXCEPTION_GROUPING}
  clickhousemetricswrite:
    endpoint: tcp://${CLICKHOUSE_DB_HOST}:${CLICKHOUSE_DB_PORT}/signoz_metrics
    resource_to_telemetry_conversion:
      enabled: true
  clickhousemetricswrite/prometheus:
    endpoint: tcp://${CLICKHOUSE_DB_HOST}:${CLICKHOUSE_DB_PORT}/signoz_metrics
  clickhouselogsexporter:
    dsn: tcp://${CLICKHOUSE_DB_HOST}:${CLICKHOUSE_DB_PORT}/signoz_logs
    docker_multi_node_cluster: ${DOCKER_MULTI_NODE_CLUSTER}
    timeout: 10s
    use_new_schema: true

service:
  pipelines:
    traces:
      receivers: [signozkafkareceiver/traces]
      exporters: [clickhousetraces]
    metrics:
      receivers: [signozkafkareceiver/metrics]
      exporters: [clickhousemetricswrite]
    logs:
      receivers: [signozkafkareceiver/logs]
      exporters: [clickhouselogsexporter]
