version: "3"

services:
  otel-collector:
    image: signoz/signoz-otel-collector:${OTELCOL_TAG:-0.102.10}
    container_name: collector-signoz-otel-collector
    command:
      [
        "--config=/etc/otel-collector-config.yaml",
        "--manager-config=/etc/manager-config.yaml",
        "--copy-path=/var/tmp/collector-config.yaml",
        "--feature-gates=-pkg.translator.prometheus.NormalizeName"
      ]
    user: root # Required for reading Docker container logs
    volumes:
      - ./otel-collector-config-signoz.yaml:/etc/otel-collector-config.yaml
      - ./otel-collector-opamp-config.yaml:/etc/manager-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /:/hostfs:ro
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=host.name=${HOST_NAME},os.type=linux
      - DOCKER_MULTI_NODE_CLUSTER=false
      - LOW_CARDINAL_EXCEPTION_GROUPING=false
      - HOST_NAME=${HOST_NAME}
      # - SIGNOZ_HOST_IP=${SIGNOZ_HOST_IP}
      - KAFKA_BROKER_1=${KAFKA_BROKER_1}
      - KAFKA_BROKER_2=${KAFKA_BROKER_2}
      - KAFKA_BROKER_3=${KAFKA_BROKER_3}
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    restart: on-failure
    mem_limit: 1g   # Limit memory to 1GB

  logspout:
    image: "gliderlabs/logspout:v3.2.14"
    container_name: collector-signoz-logspout
    volumes:
      - /etc/hostname:/etc/host_hostname:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOST_NAME=${HOST_NAME}
      # - SIGNOZ_HOST_IP=${SIGNOZ_HOST_IP}
    command: syslog+tcp://otel-collector:2255
    depends_on:
      - otel-collector
    restart: on-failure
    mem_limit: 250m   # Limit memory to 250MB


  # # Fake data
  # hotrod:
  #   image: jaegertracing/example-hotrod:1.30
  #   container_name: collector-hotrod
  #   logging:
  #     options:
  #       max-size: 50m
  #       max-file: "3"
  #   command: [ "all" ]
  #   environment:
  #     - JAEGER_ENDPOINT=http://otel-collector:14268/api/traces

  # load-hotrod:
  #   image: "signoz/locust:1.2.3"
  #   container_name: load-hotrod
  #   hostname: load-hotrod
  #   environment:
  #     ATTACKED_HOST: http://hotrod:8080
  #     LOCUST_MODE: standalone
  #     NO_PROXY: standalone
  #     TASK_DELAY_FROM: 5
  #     TASK_DELAY_TO: 30
  #     QUIET_MODE: "${QUIET_MODE:-false}"
  #     LOCUST_OPTS: "--headless -u 10 -r 1"
  #     # LOCUST_OPTS: "--headless -u 100000 -r 1000"
  #   volumes:
  #     - ./locust-scripts:/locust
